### ISSUE TITLE
Compile for Linux

### ISSUE THREAD

**Issue by blindpet** [novaroma-project/novaroma#1]
What language is this written in? Can I compile it for Linux?

**Comment by umutozel** [comment]
We only support Windows systems, for now.
We are really excited about new developments in .Net world, we will definitely try to make Novaroma cross-platform. Thanks for the feedback.

**Comment by blindpet** [comment]
Mono can be used on linux  to run .net applications. If you can tell me any other dependencies like sqlite and provide a compiled tarball i can running on linux

**Comment by umutozel** [comment]
We played with Mono when it first came out, but we are not really familiar with linux (we have not installed any dist. for years) so we do not know if porting is possible. 

Here are Nuget packages we are using;
AngleSharp, Autofac, AvalonEdit, db4o, Json.NET, Mahapps.Metro, Quartz.NET, RestSharp, SharpShell, SharpZipLib, TMDb Library, UTorrentClient Api, xmlrpcnet.

And some external references (some of them has Nuget packages but because we slightly modified their codes, we use DLLs).
Hardcodet.Wpf.TaskbarNotification, OSDBnet, Transmission.API.RPC.

It seems your mail is not public, if you could send us an email (novaroma.project@gmail.com) we can provide you everything you need.

Thank you.

**Comment by blindpet** [comment]
I will email you now, forgot about this

**Comment by Opus667** [comment]
Dude, just make a linux version...
This is the best windows tv show "manager/downloader" and now I am migrating to linux and i really miss this app

**Comment by Opus667** [comment]
Sorry for my bad education... Please make a linux version.
